#ifndef _IEAXSPKR_H
#define _IEAXSPKR_H

#define COM_NO_WINDOWS_H
#include <objbase.h>


DEFINE_GUID(DSPROPSETID_EAXVSPEAKER_Info,
0x47860820, 0x99f1, 0x11d2, 0x99, 0xe5, 0x0, 0x0, 0xe8, 0xd8, 0xc7, 0x22);

typedef enum 
{
    DSPROPERTY_EAXVSPEAKER_SELECTION,
	DSPROPERTY_EAXVSPEAKER_DIRECTION
} DSPROPERTY_EAXVSPEAKER_INFOPROPERTY;

enum
{
    EAXVSPEAKER_SELECTION_LEFT,
    EAXVSPEAKER_SELECTION_RIGHT,
    EAXVSPEAKER_SELECTION_CENTER,
    EAXVSPEAKER_SELECTION_SUPER_WOOFER,
    EAXVSPEAKER_SELECTION_SURROUND_LEFT,
    EAXVSPEAKER_SELECTION_SURROUND_RIGHT,
    EAXVSPEAKER_SELECTION_LEFT_OF_CENTER,
    EAXVSPEAKER_SELECTION_RIGHT_OF_CENTER,
    EAXVSPEAKER_SELECTION_SURROUND_CENTER,
    EAXVSPEAKER_SELECTION_SIDE_LEFT,
    EAXVSPEAKER_SELECTION_SIDE_RIGHT,
    EAXVSPEAKER_SELECTION_TOP,
    EAXVSPEAKER_SELECTION_TOP_FRONT_LEFT,
    EAXVSPEAKER_SELECTION_TOP_FRONT_CENTER,
    EAXVSPEAKER_SELECTION_TOP_FRONT_RIGHT,
    EAXVSPEAKER_SELECTION_TOP_REAR_LEFT,
    EAXVSPEAKER_SELECTION_TOP_REAR_CENTER,
    EAXVSPEAKER_SELECTION_TOP_REAR_RIGHT,
 
    EAXVSPEAKER_SELECTION_COUNT
};

#define EAXVSPEAKER_MAX_SELECTION (EAXVSPEAKER_SELECTION_COUNT - 1)



#endif  // _IEAXSPKR_H
