// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "xcardocx.h"

/////////////////////////////////////////////////////////////////////////////
// CXCardOCX

IMPLEMENT_DYNCREATE(CXCardOCX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CXCardOCX properties

long CXCardOCX::GetReadyState()
{
	long result;
	GetProperty(DISPID_READYSTATE, VT_I4, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CXCardOCX operations

VARIANT CXCardOCX::initAll()
{
	VARIANT result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::volumeUp()
{
	VARIANT result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::songAhead()
{
	VARIANT result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::songNext()
{
	VARIANT result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::songStop()
{
	VARIANT result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::songPause()
{
	VARIANT result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::songStart()
{
	VARIANT result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::volumeDown()
{
	VARIANT result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::serviceOn()
{
	VARIANT result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::serviceOff()
{
	VARIANT result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::singerOn()
{
	VARIANT result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::singerOff()
{
	VARIANT result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::songControl()
{
	VARIANT result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::exitCard()
{
	VARIANT result;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::showSongNum()
{
	VARIANT result;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::showSongN(BSTR* num)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		num);
	return result;
}

VARIANT CXCardOCX::startZhangSheng()
{
	VARIANT result;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::upAir()
{
	VARIANT result;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::airDown()
{
	VARIANT result;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::airUp()
{
	VARIANT result;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::micUp()
{
	VARIANT result;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::micDown()
{
	VARIANT result;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT CXCardOCX::setSongP(BSTR* mypd)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		mypd);
	return result;
}

VARIANT CXCardOCX::updateSLOSD(BSTR* songlist)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		songlist);
	return result;
}

void CXCardOCX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
