#if !defined(AFX_XCARDOCX_H__3C876DF1_6C8F_4987_9282_AD2D152F45C8__INCLUDED_)
#define AFX_XCARDOCX_H__3C876DF1_6C8F_4987_9282_AD2D152F45C8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CXCardOCX wrapper class

class CXCardOCX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CXCardOCX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xca9cbe8b, 0x698e, 0x4cf9, { 0xa0, 0xc2, 0x38, 0xd3, 0x89, 0xc2, 0x4b, 0x43 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetReadyState();

// Operations
public:
	VARIANT initAll();
	VARIANT volumeUp();
	VARIANT songAhead();
	VARIANT songNext();
	VARIANT songStop();
	VARIANT songPause();
	VARIANT songStart();
	VARIANT volumeDown();
	VARIANT serviceOn();
	VARIANT serviceOff();
	VARIANT singerOn();
	VARIANT singerOff();
	VARIANT songControl();
	VARIANT exitCard();
	VARIANT showSongNum();
	VARIANT showSongN(BSTR* num);
	VARIANT startZhangSheng();
	VARIANT upAir();
	VARIANT airDown();
	VARIANT airUp();
	VARIANT micUp();
	VARIANT micDown();
	VARIANT setSongP(BSTR* mypd);
	VARIANT updateSLOSD(BSTR* songlist);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_XCARDOCX_H__3C876DF1_6C8F_4987_9282_AD2D152F45C8__INCLUDED_)
